"use client";
import Image from "next/image";
import Link from "next/link";
import { ArrowRight, CaretLeft, CaretRight } from "@phosphor-icons/react";
import { AnimatePresence, motion, useReducedMotion } from "motion/react";
import { useEffect, useState } from "react";
const slides=[
 {image:"/images/services/basement-ventilation/parking-ventilation-hero.jpeg",title:"Empowering air conditioning projects",body:"Complete HVAC design, supply, installation and lifecycle support for offices, manufacturing plants, warehouses, server rooms, hospitals, hotels, laboratories and retail environments.",href:"/services"},
 {image:"/images/services/consultancy/rooftop-hvac-plant.png",title:"Engineering efficient climate systems",body:"Energy-aware HVAC solutions designed around comfort, air quality, operating reliability and long-term performance.",href:"/sustainability"},
 {image:"/images/services/consultancy/hvac-design-consultation.png",title:"Turnkey support across India",body:"One accountable engineering partner connecting surveys, design, execution, testing, commissioning and after-sales service.",href:"/gallery"}
];
export function CorporateHeroSlider(){const[active,setActive]=useState(0);const reduce=useReducedMotion();useEffect(()=>{if(reduce)return;const timer=window.setInterval(()=>setActive(v=>(v+1)%slides.length),7000);return()=>window.clearInterval(timer)},[reduce]);const go=(step:number)=>setActive(v=>(v+step+slides.length)%slides.length);const slide=slides[active];return <section className="corp-home-hero"><AnimatePresence mode="wait" initial={false}><motion.div className="hero-slide-image" key={slide.image} initial={reduce?false:{opacity:0}} animate={{opacity:1}} exit={{opacity:0}} transition={{duration:reduce?0:.55}}><Image src={slide.image} alt="HVAC engineering and project delivery" fill priority unoptimized sizes="100vw"/></motion.div></AnimatePresence><div className="corp-home-overlay"/><AnimatePresence mode="wait" initial={false}><motion.div className="site-container corp-home-copy" key={slide.title} initial={reduce?false:{opacity:0,y:18}} animate={{opacity:1,y:0}} exit={{opacity:0,y:-12}} transition={{duration:reduce?0:.42}}><span className="corp-kicker">Cawnpore Engineering Services</span><h1>{slide.title}</h1><p>{slide.body}</p><div><Link className="button button-primary" href={slide.href}>View service <ArrowRight size={18}/></Link></div></motion.div></AnimatePresence><button className="hero-arrow hero-arrow-left" type="button" onClick={()=>go(-1)} aria-label="Previous service"><CaretLeft size={30} weight="bold"/></button><button className="hero-arrow hero-arrow-right" type="button" onClick={()=>go(1)} aria-label="Next service"><CaretRight size={30} weight="bold"/></button><div className="hero-slide-dots" aria-label={`Hero slide ${active+1} of ${slides.length}`}>{slides.map((item,index)=><button className={index===active?"active":""} type="button" onClick={()=>setActive(index)} aria-label={`Show ${item.title}`} key={item.title}/>)}</div></section>}
